### ISSUE TITLE
Error: Summary() and ideal gas value

### ISSUE THREAD

**Issue by suhermantom** [johnfmaddox/kilojoule#1]
Dear Prof. Maddox,

I just found your library very useful to my work. This has been the library I have been searching to teach Thermodynamics in the future.

However, I have found an issue when running for `Summary()`, it always shows the following:

`ValueError: If using all scalar values, you must pass an index`
I assume it is due to the updated `pandas` lib, which needs an index to be stated, but it could be something else.

In addition, I have some doubts in the properties of ideal gas. I found the differences to that of the textbook (say, Cengel & Boles) are quite big. Is the any reason for it?

Please help.

Best,
Mo Suhermanto

**Comment by johnfmaddox** [comment]
Hi Mo,

Thanks for reaching out.  I'm glad you found the library useful.

Yes, I'm familiar with that error and I believe you are correct that it is
due to a pandas update that broke backwards compatibility.  I've also seen
some issues when trying to use the library with newer versions of python
(>3.8), but those may also be due to the Pandas updates. Either way, that
error should be fixed in the devel branch.  I've been meaning to update the
main branch and the Pypi package, but my summer has been busier than
expected.  If you don't want to switch to the devel branch, that error
should only impact the printing done by the Summary() command.  It should
not impact any of the calculations.

Note: there have been some changes to the syntax in the devel branch that
break backward compatibility, so if you are just getting started with the
library and intend to use it for teaching, I recommend you go ahead and
move to the devel branch.  My students use the devel branch.

The discrepancies you see between the property values from different
sources, i.e. the tables in the kilojoule library vs Cengel & Boles, are
probably a result of using different reference states for integrated
properties such as internal energy, enthalpy, and entropy.  Since u, h, and
s are integrated relative to an arbitrary reference state, different
sources will report different "absolute" values for those quantities, but
the differences between states for u, h, and s should be consistent between
different textbooks (and with the kilojoule library).  You should see good
agreement for the absolute values of T, p, and v between the kilojoule
library and the appendix of Cengel & Boles.  You should also see good
agreement for (delta u), (delta h), and (delta s) between any two arbitrary
states even though the absolute values for those quantities are different
in the library than the textbook.

I have been teaching from the Cengel & Boles Thermodynamics text as well as
I've been developing this library and adding an option to adjust the
reference state used by the library to match the textbook has been on my
to-do list for a while, but I haven't gotten around to it yet.

I hope to push more updates in the coming weeks as the fall semester gets
underway.

Hope this helps,
Jack


John F. Maddox, Ph.D., P.E.
he/him/his
Associate Professor
University of Kentucky
Mechanical Engineering
Paducah Campus
4810 Alben Barkley Dr
Paducah, KY 42001
270-534-3119
***@***.***
Schedule Meeting Online
***@***.***/bookings/>

**Comment by suhermantom** [comment]
Dear Dr. Maddox,

Thank you very much for your response.

I have used your wonderful `kilojoule` library and will most likely create many education materials using it.

So far, I have tried many different settings of the library, and my note for the supporting libraries are as follows for the best result (for now):

Python==3.8.8
pandas==1.1.5
matplotlib==3.5.3
scipy==1.9.1
sympy==1.11.1
numpy==1.23.2
kilojoule==0.2.9

Perhaps, the list is useful for `yaml` usage. 

In addition, I am writing some of Thermo of Moran-Saphiro book problems using this library, along with our own Thermo 1 course material. 

It will be great if someday I have the honor to collaborate with you for more educational materials. Sadly, I am currently busy of finishing my PhD which is not thermo-heavy subject. However, I will teach Thermo when I go back home to Indonesia. Thus, this library is highly relevant to my future career.

Sincerely,
Mo
